### ISSUE TITLE
How to exclude node_modules and other directories from the scan?

### ISSUE THREAD

**Issue by ausshadu** [Checkmarx/ast-azure-plugin#452]
### Describe the bug
I have a react project, and I would like to exclude node_modules and other specific directories

The Azure Pipeline task is below

```yml
- task: Checkmarx AST@2
  displayName: 'Checkmarx AST'
  condition: and(always(), eq('${{ parameters.ShouldRunCheckMarx }}', true))
  continueOnError: true
  inputs:
    CheckmarxService: 'CheckMarx-Connection'
    projectName: $(Build.Repository.Name)
    branchName: $(Build.SourceBranchName)
    tenantName: ${{ parameters.tenantName }}
    additionalParams: |
      --file-filter '!node_modules'
```

This is not working.
